Repository GarnBarn/garnbarn-backend, pull requests merged in 2021-11, with the labels that each got.

#30 HotFix: CustomUser is not JSON serializable
  garnbarn_api/serializer.py
  garnbarn_api/tests/test_view.py
  garnbarn_api/views.py
Labels: bug

#32 Update all serializer
  garnbarn_api/models.py
  garnbarn_api/serializer.py
  garnbarn_api/tests/test_serializer.py
  garnbarn_api/tests/test_tag_serializer.py
  garnbarn_api/tests/test_view.py
  garnbarn_api/views.py
Labels: bug

#33 Tag Subscribtion/Unsubscribtion
  garnbarn_api/migrations/0028_auto_20211104_0214.py
  garnbarn_api/migrations/0029_auto_20211104_0218.py
  garnbarn_api/migrations/0030_merge_0028_auto_20211104_1010_0029_auto_20211104_0218.py
  garnbarn_api/tests/test_view.py
  garnbarn_api/urls.py
  garnbarn_api/views.py
Labels: enhancement

#38 User API
  .gitignore
  README.md
  garnbarn_api/authentication.py
  garnbarn_api/serializer.py
  garnbarn_api/services/line.py
  garnbarn_api/urls.py
  garnbarn_api/views.py
  requirements.txt
Labels: enhancement

#44 Change CI
  .github/workflows/django_test.yml
  .travis.yml
  README.md
Labels: P0

#45 Iteration4
  config/settings.py
  garnbarn_api/apps.py
  garnbarn_api/models.py
  garnbarn_api/serializer.py
  garnbarn_api/services/__init__.py
  garnbarn_api/services/pubsub.py
  garnbarn_api/services/scheduler.py
  garnbarn_api/tests/test_scheduler.py
  requirements.txt
Labels: enhancement

#50 Iteration5
  .github/workflows/django_test.yml
  README.md
  config/settings.py
  garnbarn_api/admin.py
  garnbarn_api/apps.py
  garnbarn_api/authentication.py
  garnbarn_api/models.py
  garnbarn_api/serializer.py
  garnbarn_api/services/line.py
  garnbarn_api/services/line_message_generator.py
  garnbarn_api/services/notification/__init__.py
  garnbarn_api/services/notification/platforms/__init__.py
  garnbarn_api/services/notification/platforms/line.py
  garnbarn_api/services/notification/platforms/notification_platform.py
  garnbarn_api/services/notification/send_notification.py
  garnbarn_api/services/pubsub.py
  garnbarn_api/signals/__init__.py
  garnbarn_api/signals/on_save_assignment_signal.py
  garnbarn_api/signals/publish_notification_signal.py
  garnbarn_api/tests/test_view.py
  garnbarn_api/urls.py
  garnbarn_api/views.py
Labels: enhancement

#51 BUG fixed: wrong declaration - timezone
  garnbarn_api/services/line_message_generator.py
  garnbarn_api/services/notification/platforms/notification_platform.py
Labels: HotFix

#54 Update schedule when tag is updated
  garnbarn_api/apps.py
  garnbarn_api/models.py
  garnbarn_api/serializer.py
  garnbarn_api/signals/on_save_assignment_signal.py
Labels: bug
